SERIES_CONFIG = {
    "WTI": {
        "source": "fred",
        "series_id": "DCOILWTICO",
        "name": "WTI Crude Oil Price",
        "unit": "USD/barrel",
        "category": "energy",
        "valid_min": -5.0,
        "valid_max": 200.0,
        "frequency": "daily",
    },
    "BRENT": {
        "source": "fred",
        "series_id": "DCOILBRENTEU",
        "name": "Brent Crude Oil Price",
        "unit": "USD/barrel",
        "category": "energy",
        "valid_min": 0.0,
        "valid_max": 200.0,
        "frequency": "daily",
    },
    "SP500": {
        "source": "yfinance",
        "series_id": "^GSPC",
        "name": "S&P500",
        "unit": "index",
        "category": "equity",
        "valid_min": 100.0,
        "valid_max": 20000.0,
        "frequency": "daily",
    },
    "NASDAQ": {
        "source": "yfinance",
        "series_id": "^IXIC",
        "name": "NASDAQ Composite",
        "unit": "index",
        "category": "equity",
        "valid_min": 100.0,
        "valid_max": 30000.0,
        "frequency": "daily",
    },
    "FED_FUNDS": {
        "source": "fred",
        "series_id": "FEDFUNDS",
        "name": "Federal Funds Effective Rate",
        "unit": "percent",
        "category": "rates",
        "valid_min": 0.0,
        "valid_max": 25.0,
        "frequency": "monthly"
    },
    "CPI": {
        "source": "fred",
        "series_id": "CPIAUCSL",
        "name": "Consumer Price Index (All Urban)",
        "unit": "index",
        "category": "macro",
        "valid_min": 10.0,
        "valid_max": 500.0,
        "frequency": "monthly",
    },
    "GOLD": {
        "source": "yfinance",
        "series_id": "GC=F",
        "name": "Gold Futures",
        "unit": "USD/oz",
        "category": "macro",
        "valid_min": 100.0,
        "valid_max": 5000.0,
        "frequency": "daily",
    },
    "T10Y": {
        "source": "fred",
        "series_id": "DGS10",
        "name": "10-Year Treasury Constant Maturity Rate",
        "unit": "percent",
        "category": "rates",
        "valid_min": -1.0,
        "valid_max": 20.0,
        "frequency": "daily",
    },
    "T2Y": {
        "source": "treasury",
        "series_id": "BC_2YEAR",
        "name": "2-Year Treasury Yield",
        "unit": "percent",
        "category": "rates",
        "valid_min": -1.0,
        "valid_max": 20.0,
        "frequency": "daily",
    },
    "T10Y_TREASURY": {
        "source": "treasury",
        "series_id": "BC_10YEAR",
        "name": "10-Year Treasury Yield",
        "unit": "percent",
        "category": "rates",
        "valid_min": -1.0,
        "valid_max": 20.0,
        "frequency": "daily",
    },
    "EURUSD": {
        "source": "alphavantage",
        "series_id": "EUR/USD",
        "name": "Euro / US Dollar Exchange Rate",
        "unit": "USD",
        "category": "forex",
        "valid_min": 0.5,
        "valid_max": 2.0,
        "frequency": "daily",
    },
    "VIX": {
        "source": "yfinance",
        "series_id": "^VIX",
        "name": "CBOE Volatility Index",
        "unit": "index",
        "category": "equity",
        "valid_min": 5.0,
        "valid_max": 90.0,
        "frequency": "daily",
    },
    "YIELD_SPREAD": {
        "source": "derived",
        "series_id": "DERIVED_YIELD_SPREAD",
        "name": "Yield Curve Spread (10Y - 2Y)",
        "unit": "percent",
        "category": "derived",
        "valid_min": -5.0,
        "valid_max": 10.0,
        "frequency": "daily",
    },
    "REAL_WTI": {
        "source": "derived",
        "series_id": "DERIVED_REAL_WTI",
        "name": "Real WTI Crude Oil Price (CPI-adjusted)",
        "unit": "USD/barrel",
        "category": "derived",
        "valid_min": -5.0,
        "valid_max": 200.0,
        "frequency": "daily",
    },
    "WTI_SP500": {
        "source": "derived",
        "series_id": "DERIVED_WTI_SP500",
        "name": "WTI to S&P500 Ratio",
        "unit": "ratio",
        "category": "derived",
        "valid_min": 0.0,
        "valid_max": 100.0,
        "frequency": "daily",
    },
}

def get_source_series(source: str) -> dict:
    return {series_key: data for series_key, data in SERIES_CONFIG.items() if data["source"] == source}

def get_series(series_key: str) -> dict:
    return SERIES_CONFIG[series_key]

def get_field(series: str, field: str) -> str:
    return SERIES_CONFIG[series][field]